# version: '3.9' # This now uses Compose Spec (https://github.com/compose-spec/compose-spec/blob/master/spec.md)

x-pltsci-sdet-assignment-template: &pltsci-sdet-assignment-template
  image: ${REGISTRY_URI:-}${DOCKER_NAMESPACE:-}pltsci-sdet-assignment${IMAGE_VERSION:-:latest}
  build:
    context: ./service
    dockerfile: Dockerfile
  # run as non-root. good for security and the ability for the test container to manipulate the log file
  user: www-data
  volumes:
    - application_home:/usr/local/demo-app
  # This health check allow the indication of a healthy container.  It also gives the ability to the tests
  # to restart the server when paired with a health monitor
  labels:
    autoheal.stop.timeout: 1
    autoheal: "true"
  restart: always
  entrypoint: ["/usr/bin/java"]
  expose:
    - 8080

x-pltsci-sdet-assignment-healthcheck-template: &pltsci-sdet-assignment-healthcheck-template
  interval: 1s
  timeout: 1s
  retries: 0
  start_period: 20s

services:
  # This container just fixes some permissions then shuts down (init container)
  startup:
    image: ${REGISTRY_URI:-}${DOCKER_NAMESPACE:-}pltsci-sdet-assignment-tests${IMAGE_VERSION:-:latest}
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    entrypoint: [ "/bin/bash", "/test_compose_init_entrypoint.sh" ]
    command: []
    volumes:
      - application_home:/usr/local/demo-app
    depends_on:
      - pltsci-sdet-assignment-8081
      - pltsci-sdet-assignment-8082
      - pltsci-sdet-assignment-8083
      - pltsci-sdet-assignment-8084
      - pltsci-sdet-assignment-8085

  codeceptjs:
    image: ${REGISTRY_URI:-}${DOCKER_NAMESPACE:-}pltsci-sdet-assignment-tests${IMAGE_VERSION:-:latest}
    build:
      context: .
      dockerfile: Dockerfile
    user: pwuser
    container_name: pltsci-sdet-assignment-tests
    depends_on:
      - pltsci-sdet-assignment-8081
      - pltsci-sdet-assignment-8082
      - pltsci-sdet-assignment-8083
      - pltsci-sdet-assignment-8084
      - pltsci-sdet-assignment-8085
      - autoheal
      - startup
    entrypoint: ["/usr/bin/node", "/src/test/javascript/sdet-assignment-service-codeceptsjs/node_modules/codeceptjs/bin/codecept.js"]
    command: ["run-workers", "5", "--plugins", "allure"]
    volumes:
      - application_home:/usr/local/demo-app
      - test_output:/src/test/javascript/sdet-assignment-service-codeceptsjs/test_output
    environment:
      SERVER_IS_EXTERNAL: "true"
      TARGET_BASE_URI: http://pltsci-sdet-assignment-%s:8080
      ALLOW_TEST_FAILURES: "true"

  pltsci-sdet-assignment-8081:
    <<: *pltsci-sdet-assignment-template
    container_name: pltsci-sdet-assignment-8081
    healthcheck:
      <<: *pltsci-sdet-assignment-healthcheck-template
      # If the log file exists, we will assume the application has started successfully
      test: ["CMD-SHELL", "[ -f /usr/local/demo-app/logs/application-1.log ]"]
    # We could possibly make use of extends here if we wanted to make a seperate yml file
    command:
      - "-Dlogging.file=/usr/local/demo-app/logs/application-1.log"
      - "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
      - "-Dproperties.location=/application.properties"
      - "-Xdebug"
      - "-jar"
      - "/usr/local/demo-app/sdet-assignment-service-0.0.1-SNAPSHOT.jar"

  pltsci-sdet-assignment-8082:
    <<: *pltsci-sdet-assignment-template
    container_name: pltsci-sdet-assignment-8082
    healthcheck:
      <<: *pltsci-sdet-assignment-healthcheck-template
      # If the log file exists, we will assume the application has started successfully
      test: ["CMD-SHELL", "[ -f /usr/local/demo-app/logs/application-2.log ]"]
    # We could possibly make use of extends here if we wanted to make a seperate yml file
    command:
      - "-Dlogging.file=/usr/local/demo-app/logs/application-2.log"
      - "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
      - "-Dproperties.location=/application.properties"
      - "-Xdebug"
      - "-jar"
      - "/usr/local/demo-app/sdet-assignment-service-0.0.1-SNAPSHOT.jar"

  pltsci-sdet-assignment-8083:
    <<: *pltsci-sdet-assignment-template
    container_name: pltsci-sdet-assignment-8083
    healthcheck:
      <<: *pltsci-sdet-assignment-healthcheck-template
      # If the log file exists, we will assume the application has started successfully
      test: ["CMD-SHELL", "[ -f /usr/local/demo-app/logs/application-3.log ]"]
    # We could possibly make use of extends here if we wanted to make a seperate yml file
    command:
      - "-Dlogging.file=/usr/local/demo-app/logs/application-3.log"
      - "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
      - "-Dproperties.location=/application.properties"
      - "-Xdebug"
      - "-jar"
      - "/usr/local/demo-app/sdet-assignment-service-0.0.1-SNAPSHOT.jar"

  pltsci-sdet-assignment-8084:
    <<: *pltsci-sdet-assignment-template
    container_name: pltsci-sdet-assignment-8084
    healthcheck:
      <<: *pltsci-sdet-assignment-healthcheck-template
      # If the log file exists, we will assume the application has started successfully
      test: ["CMD-SHELL", "[ -f /usr/local/demo-app/logs/application-4.log ]"]
    # We could possibly make use of extends here if we wanted to make a seperate yml file
    command:
      - "-Dlogging.file=/usr/local/demo-app/logs/application-4.log"
      - "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
      - "-Dproperties.location=/application.properties"
      - "-Xdebug"
      - "-jar"
      - "/usr/local/demo-app/sdet-assignment-service-0.0.1-SNAPSHOT.jar"

  pltsci-sdet-assignment-8085:
    <<: *pltsci-sdet-assignment-template
    container_name: pltsci-sdet-assignment-8085
    healthcheck:
      <<: *pltsci-sdet-assignment-healthcheck-template
      # If the log file exists, we will assume the application has started successfully
      test: ["CMD-SHELL", "[ -f /usr/local/demo-app/logs/application-5.log ]"]
    # We could possibly make use of extends here if we wanted to make a seperate yml file
    command:
      - "-Dlogging.file=/usr/local/demo-app/logs/application-5.log"
      - "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
      - "-Dproperties.location=/application.properties"
      - "-Xdebug"
      - "-jar"
      - "/usr/local/demo-app/sdet-assignment-service-0.0.1-SNAPSHOT.jar"

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - startup
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: "1"   # check every 5 seconds
      AUTOHEAL_START_PERIOD: "0"   # wait 0 seconds before first health check
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: "10"   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      DOCKER_SOCK: /var/run/docker.sock   # Unix socket for curl requests to Docker API
      CURL_TIMEOUT: "30"     # --max-time seconds for curl requests to Docker API

volumes:
  application_home:
  test_output:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/test_output
      o: bind